type TQuestionCategory =
	| "React"
	| "GraphQL"
	| "Node.js"
	| "TypeScript"
	| "JavaScript"
	| "CSS"
	| "HTML"
	| "Redux"
	| "Next.js"
	| "Express.js"
	| "MongoDB"
	| "SQL"
	| "REST API"
	| "WebSockets"
	| "Testing"
	| "Performance Optimization"
	| "Security"
	| "Authentication & Authorization"
	| "State Management"
	| "Design Patterns"
	| "Architecture"
	| "Deployment & DevOps"
	| "CI/CD"
	| "Microservices"
	| "Serverless"
	| "Web Accessibility"
	| "Progressive Web Apps (PWA)"
	| "GraphQL Subscriptions"
	| "WebRTC"
	| "WebAssembly"
	| "Machine Learning in JS"
	| "Data Visualization"
	| "Mobile Development with React Native"
	| "Cross-Browser Compatibility"
	| "Internationalization (i18n)"
	| "Localization (l10n)"
	| "Web Components"
	| "Service Workers"
	| "Caching Strategies"
	| "Content Delivery Networks (CDN)"
	| "API Rate Limiting"
	| "OAuth 2.0 & OpenID Connect"
	| "JWT (JSON Web Tokens)"
	| "Single Page Applications (SPA)"
	| "Multi-Page Applications (MPA)"
	| "Server-Side Rendering (SSR)"
	| "Client-Side Rendering (CSR)"
	| "Static Site Generation (SSG)"
	| "Jamstack Architecture"
	| "jQuery"
	| "jQuery 4";

export default interface IQuestion {
	id: number;
	title: string;
	category: TQuestionCategory;
	answer: string;
}
